name: usermanagement
description: Api for signin and singup
version: 0.0.1
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/usermanagement
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  rpc: any
  mailer: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
